---
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - loki
      - prometheus
    networks:
      - logging

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logging

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/log:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - logging
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - logging

  log-generator:
    image: busybox
    command: /bin/sh -c "while true; do echo \"$(date +'%Y-%m-%dT%H:%M:%S') [INFO] Action performed successfully.\"; sleep 1; done"
    volumes:
      - ./log:/var/log
    networks:
      - logging

networks:
  logging: